#
# Copyright © 2013-2018, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

application:
  id: ddd

logging: INFO

mongoDb:
  clients:
    main:
      databases: dddSample
      uri: ${env.DB_URL}

classes:
  org:
    seedstack:
      samples:
        ddd:
          domain:
            model:
              defaultRepository: org.seedstack.mongodb.morphia.Morphia
              mongoDbClient: main
              mongoDbDatabase: dddSample
