#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

myApp:
  key: value
  macro: '*${myApp.key}*'
  environmentVariable: ${env.JAVA_HOME}
  systemProperty: ${sys.java\\.version}
  country: FR

security:
  users:
    alice:
      password: password
      roles: ADMIN.FR
    bob:
      password: password
      roles: ADMIN.DE
    carol:
      password: password
      roles: EDITOR
    dave:
      password: password
  roles:
    admin: ADMIN.{location}
    editor: EDITOR
    guest: '*'
  permissions:
    admin: ['user:*', 'article:*']
    editor: ['article:create', 'article:edit', 'article:delete']
